#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] = File.join(File.dirname(__FILE__), 'Gemfile')

require 'rubygems'
require 'bundler/setup'

require 'fileutils'
require 'taglib'

DEFAULT_GENRE = nil # 'untagged'

album_name = ARGV[0]

puts 'Detecting MP3 files...'
Dir.glob('*.mp3') do |file|
  filename = File.basename(file, '.mp3')
  parts = filename.split('-')
  artist = parts.shift
  song = parts.join(' - ')

  # puts 'Updating ID3 tags ...'
  TagLib::FileRef.open(file) do |f|
    unless f.null?
      f.tag.artist = f.tag.artist
      f.tag.album = album_name
      f.tag.title = f.tag.title

      # update tags
      f.save
    end
  end

  puts "Set album to #{album_name}"
  puts '*' * 20
end
