#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] = File.join(File.dirname(__FILE__), 'Gemfile')

require 'rubygems'
require 'bundler/setup'

require 'fileutils'

current_dir = Dir.pwd

def convert_files(extension)
  puts "Detecting #{extension.upcase} files ..."
  Dir.glob("*.#{extension}") do |file|
    name = File.basename(file, ".#{extension}")

    puts "Creating '#{name}.mp3' from '#{file}' using lame ..."
    `lame -b 320 -h "#{file}" "#{name}.mp3"`
    FileUtils.mv file, File.expand_path('~/Desktop/Originals/'), :noop => false, :verbose => true
  end
end

convert_files('wav')
convert_files('aif')
