#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] = File.join(File.dirname(__FILE__), 'Gemfile')

require 'open-uri'
require 'rubygems'
require 'bundler/setup'

def usage
  puts 'Please pass a url to check'
  puts
  puts "usage: scov https://soundcloud.com/artist/track"
end

if ARGV.size > 0
  url = ARGV.pop
else
 usage
 exit
end

require 'soundcloud'
require 'dotenv'
Dotenv.load(File.join(File.dirname(__FILE__), '.env'))

target_dir       = File.expand_path("~/Downloads")
client           = Soundcloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'])
track            = client.get('/resolve', :url => url)
artwork_filename = "#{track.user.username} - #{track.title}.jpg"

begin
  File.open(File.join(target_dir, artwork_filename), "wb") do |saved_file|
    open(track.artwork_url.gsub('large','t500x500'), "rb") do |read_file|
      saved_file.write(read_file.read)
    end
  end

  puts "Downloaded #{artwork_filename} to #{target_dir}"

rescue => e
  puts e
end
