#!/bin/bash

target="$HOME/Desktop/Personal/Transfer/"
current_dir=$(pwd)

if [ -t 0 ]; then
  mv "$current_dir/$1" "$target"
else
  while read line ; do
    mv "$current_dir/$line" "$target"
  done
fi
